### ISSUE TITLE
Japanese Translation Error on the Release Note Page

### ISSUE THREAD

**Issue by yasuoo-netapp** [NetAppDocs/bluexp-classification.ja-jp#1]
### Page URL

https://docs.netapp.com/ja-jp/bluexp-classification/whats-new.html

### Page title

BlueXP分類の新機能

### Summary

The text reads 'タツシユホトノツイカテタ'.
The correct translation of this is 'ダッシュボードの追加データ'.

On the English page, it is written as 'Additional data in dashboards'.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-gudugunti** [comment]
Thanks! for reporting the issue, @yasuoo-netapp.
The issue will be reviewed by the translation team.
Shall get back to you on this as soon as I hear from them.

**Comment by netapp-gudugunti** [comment]
Thanks! for your patience.
The issue is resolved.
